name: Deploy Flutter Web

on:
  push:
    branches:
      - main  # Senin ana dalın 'master' ise burayı 'master' yap!

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Flutter Kur
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Bağımlılıkları Yükle
        run: |
          cd energy_app
          flutter pub get

      - name: Web İçin Derle
        # BURASI ÖNEMLİ: Repo ismin SolarEMS değilse tırnak içini değiştir
        run: |
          cd energy_app
          flutter build web --release --base-href "/SolarEMS/" --no-tree-shake-icons

      - name: GitHub Pages'e Gönder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./energy_app/build/web
